config/routes.rb
Rails.application.routes.draw do
   get 'admin/login'
  get 'admin/logout'
  get 'admin/settings'
  get 'reports/students'
  get 'reports/schools'
  get 'reports/health_sessions'
  get 'reports/daily_community_visits'
  get 'reports/monthly_school_visits'
  get 'reports/daily_school_visits'
  get 'reports/environment_assessments'

  get 'admin/get_charts'
  get 'admin/update_tiles'
  get 'admin/update_movement_map'
  get 'admin/update_planning_report'
  get 'admin/update_tehsils'
  get 'admin/update_schools'
  get 'admin/update_districts'
  get 'admin/school_details'
  get 'admin/env_assesment_details'
  get 'admin/health_sessions_details'
  get 'admin/std_assesment_details'
  get 'admin/council_meetings_details'
  get 'admin/update_shns'
  get 'admin/update_movement_map'

  post 'admin/session_login'
  post 'admin/save_settings'

  get 'admin/manage_districts'
  get 'admin/manage_divisions'
  get 'admin/manage_ucs'
  get 'admin/edit_division'
  get 'admin/edit_tehsil'
  get 'admin/edit_district'
  get 'admin/edit_uc'
  get 'admin/delete_division'
  get 'admin/delete_district'
  get 'admin/delete_tehsil'
  get 'admin/delete_uc'
  get 'admin/delete_staff'
  get 'admin/manage_tehsils'

  get 'admin/manage_staff'
  get 'admin/manage_shns'
  get 'admin/manage_schools'
  get 'admin/delete_school'
  get 'admin/delete_shns'
  get 'admin/new_staff_member'
  get 'admin/edit_staff'
  get 'admin/new_shns_member'
  get 'admin/export_data'
  get 'admin/community_daily_reporting'
  get 'admin/monthly_school_visits'
  get 'admin/daily_school_visits'
  get 'admin/track_agents'

  get 'admin/division_details'
  get 'admin/district_details'
  get 'admin/tehsil_details'
  get 'admin/update_staff_status'
  get 'admin/school_details'

  post 'admin/create_new_school'
  post 'admin/create_new_shns'
  post 'admin/create_new_staff'
  post 'admin/export_data'
  post 'admin/create_new_district'
  post 'admin/update_district'
  post 'admin/update_staff'
  post 'admin/update_tehsil'
  post 'admin/create_new_division'
  post 'admin/update_division'
  post 'admin/update_uc'
  post 'admin/create_new_uc'
  post 'admin/create_new_tehsil'

  get 'admin/dashboard'
  get 'admin/new_agent'

  post 'api/login', :defaults => { :format => 'json' }
  post 'api/agent_location_log', :defaults => { :format => 'json' }
  post 'api/create_student', :defaults => { :format => 'json' }
  post 'api/get_nearby_schools', :defaults => { :format => 'json' }
  get 'api/search_schools_for_select', :defaults => { :format => 'json' }
  get 'api/search_tehsil_for_select', :defaults => { :format => 'json' }
  get 'api/search_districts_for_select', :defaults => { :format => 'json' }
  post 'api/search_schools', :defaults => { :format => 'json' }
  post 'api/search_uc', :defaults => { :format => 'json' }
  post 'api/get_ucs', :defaults => { :format => 'json' }
  post 'api/submit_health_session', :defaults => { :format => 'json' }
  post 'api/submit_child_health_screening', :defaults => { :format => 'json' }
  post 'api/submit_environment_assesment', :defaults => { :format => 'json' }
  post 'api/submit_council_meeting', :defaults => { :format => 'json' }
  post 'api/submit_add_child', :defaults => { :format => 'json' }
  post 'api/submit_planner_record', :defaults => { :format => 'json' }
  post 'api/submit_add_child_health_screening', :defaults => { :format => 'json' }

  get 'graph/students_assessed_by_day', :defaults => { :format => 'json' }
  get 'graph/followups_by_day', :defaults => { :format => 'json' }
  get 'graph/schools_visited_by_day', :defaults => { :format => 'json' }
  get 'graph/health_sessions_by_day', :defaults => { :format => 'json' }
  get 'graph/environmental_assesments_by_day', :defaults => { :format => 'json' }

  root 'admin#login'

end

app/views/admin/_district_tables.html.erb
<div class="row">
  
<div class="col-md-10 col-md-offset-1">
    <!-- START PANEL -->
    <div class="panel panel-transparent">
      <div class="panel-heading">
        <div class="panel-title"> <h1> <%= !params[:division].present? ? "All Districts" : "Districts in #{@division.name}" %></h1>
        </div>
      </div>
      <div class="panel-body">

        <%= form_tag admin_manage_districts_path , :multipart => true ,role: "form",method: :get, novalidate: "novalidate", autocomplete: "off", id: "form-personal" do %>

             
              <div class="row">
                  
                <div class="col-sm-3">
                <div class="form-group form-group-default " >
                  <label>Select Division</label>
                    <%= select_tag 'division',  content_tag(:option,'No Filter',:value=>"") +options_from_collection_for_select(Division.all,"id","name", params[:division]),class: "form-control", required: "" %>
                </div>
              </div>
            

              </div>
              <div class="clearfix"></div>
              <button class="btn btn-primary" type="submit">Filter</button>
              <%= link_to "Clear Filter", admin_manage_districts_path, class: "btn btn-primary pull-right" %>
            <% end %>
        <div class="table-responsive">
          <div id="detailedTable_wrapper" class="dataTables_wrapper form-inline no-footer"><table class="table table-hover table-condensed table-detailed dataTable no-footer" id="detailedTable" role="grid">
            <thead>
              <tr role="row">
              <th style="width:45%" rowspan="1" colspan="1">Name</th>
              <th style="width:20%" rowspan="1" colspan="1">Division</th>
              <th style="width:20%" rowspan="1" colspan="1">Tehsils</th>
              <th style="width:20%" rowspan="1" colspan="1">UCs</th>
              <th style="width:20%" rowspan="1" colspan="1">Schools</th>
              <th style="width:10%" rowspan="1" colspan="1">Edit </th>
              <th style="width:10%" rowspan="1" colspan="1">Delete </th>

              </tr>
            </thead>
            <tbody>
              
              
            <tr role="row" class="odd">
              <% @districts.each do |district| %>
                <td class="v-align-middle semi-bold"><%= district.name %></td>
                <td class="v-align-middle semi-bold"><%= district.division_name %></td>
                <td class="v-align-middle">
                       <%= link_to admin_manage_tehsils_path(dis: district.id) do %>
                          <%= district.tehsils_count %>
                       <% end %>
                    </td>
                    <td class="v-align-middle">
                       <%= link_to admin_manage_ucs_path(dis: district.id) do %>
                          <%= district.ucs_count  %>
                       <% end %>
                    </td>

                    <td class="v-align-middle">
                       <%= link_to admin_manage_schools_path(dis: district.id) do %>
                          <%= district.schools_count %>
                       <% end %>
                    </td>
                <td class="v-align-middle"><%= link_to '<i class="fa fa-wrench"></i>'.html_safe , admin_edit_district_path(dis: district.id), remote: true %></td>
                <td class="v-align-middle"><%= link_to '<i class="fa fa-trash"></i>'.html_safe , admin_delete_district_path(dis_id: district.id) %></td>
                
              </tr>
            <% end %>
              </tbody>
          </table></div>
        </div>
      </div>
    </div>
    <!-- END PANEL -->
  </div>
</div>  

app/views/admin/_export_data_students.html.erb
 <div class="row">
<div class="col-md-8 col-md-offset-2">
<h1>Export Student Data</h1>
<!-- START PANEL -->
<div class="panel panel-transparent">
  <div class="panel-body">

    <%= form_tag reports_students_path , :multipart => true ,role: "form",method: :get, novalidate: "novalidate", autocomplete: "off", id: "form-personal" do %>

      <% if flash[:alert].present? %>
        <div class="row clearfix">

          <div class="alert <%= flash[:alert_class] %>" role="alert">
            <button class="close" data-dismiss="alert"></button>
            <strong><%= flash[:alert_start] %>: </strong><%= flash[:alert] %>
          </div>
        </div>

      <% end %>
        <div class="row clearfix student">
          <div class="col-sm-12">
          <div class="form-group form-group-default required" aria-required="true">
            <label>Select Destrict</label>
              <%= select_tag 'district', content_tag(:option,'Please select District',:value=>"") + options_from_collection_for_select(@districts,"id","name_with_division"),class: "form-control", required: "", id: "district_select" %>
          </div>
        </div>
        </div>

           <div class="row clearfix">
          <div class="col-sm-12">
          <div class="form-group form-group-default required" aria-required="true">
            <label>Select Tehsil</label>
              <%= select_tag 'tehsil',  content_tag(:option,'Please Select Tehsil',:value=>"")+ options_from_collection_for_select(@tehsils,"id","name_with_district"),class: "form-control", required: "", id: "tehsil_select" %>
          </div>
        </div>
        </div>

        <div class="row clearfix">
          <div class="col-sm-12">
          <div class="form-group form-group-default required" aria-required="true">
            <label>Select School</label>
              <%= select_tag 'school',  content_tag(:option,'Please Select School',:value=>"")+ options_from_collection_for_select(@schools,"id","name"),class: "form-control", required: "", id: "school_select" %>
          </div>
        </div>
        </div>
        <div class="row clearfix">

        <div class="col-sm-12">
          <div class="form-group form-group-default required" aria-required="true">
          <label>Select Range</label>
            <input type="text" name="range" id="reportrange_students" class="pull-right" style="background: #fff; cursor: pointer; padding: 5px 10px; border: 1px solid #ccc; width: 100%">
              </input>
        </div>
        </div>        
        <div class="row clearfix">
          <div class="form-group required student" >
          
          <div class="col-sm-3">
            <label>Select Attributes</label>
             
              <div class="checkbox check-success">
                <input type="checkbox" checked="checked" value="name" id="name" name="cols[]">
                <label for="name">Name</label>
              </div>
  
              <div class="checkbox check-success">
                <input type="checkbox" checked="checked" value="gaurdian_name" id="gaurdian_name" name="cols[]">
                <label for="gaurdian_name">Gaurdian Name</label>
              </div>

              <div class="checkbox check-success">
                <input type="checkbox" checked="checked" value="father_name" id="father_name" name="cols[]">
                <label for="father_name">Father Name</label>
              </div>
            
              <div class="checkbox check-success">
                <input type="checkbox" checked="checked" value="siblings" id="siblings" name="cols[]">
                <label for="siblings">Siblings</label>
              </div>

          </div>

          <div class="col-sm-3">             
              <div class="checkbox check-success">
                <input type="checkbox" checked="checked" value="hieght" id="hieght" name="cols[]">
                <label for="hieght">Height</label>
              </div>
  
              <div class="checkbox check-success">
                <input type="checkbox" checked="checked" value="weight" id="weight" name="cols[]">
                <label for="weight">Weight</label>
              </div>
              
              <div class="checkbox check-success">
                <input type="checkbox" checked="checked" value="last_assessed" id="last_assessed" name="cols[]">
                <label for="last_assessed">Last Assessed</label>
              </div>

              
              <div class="checkbox check-success">
                <input type="checkbox" checked="checked" value="trauma_physical_injuries" id="trauma_physical_injuries" name="cols_health[]">
                <label for="trauma_physical_injuries">Trauma/Physical Injs.</label>
              </div> 

              <div class="checkbox check-success">
                <input type="checkbox" checked="checked" value="bmi" id="bmi" name="cols_health[]">
                <label for="bmi">Bmi</label>
              </div>
          </div>

          <div class="col-sm-3">             
  
              <div class="checkbox check-success">
                <input type="checkbox" checked="checked" value="anemia" id="anemia" name="cols_health[]">
                <label for="anemia">Anemia</label>
              </div>

              <div class="checkbox check-success">
                <input type="checkbox" checked="checked" value="physical_deformities" id="physical_deformities" name="cols_health[]">
                <label for="physical_deformities">Physical Deformities</label>
              </div>
            
              <div class="checkbox check-success">
                <input type="checkbox" checked="checked" value="hearing_problem" id="hearing_problem" name="cols_health[]">
                <label for="hearing_problem">Hearing Problem</label>
              </div> 

              <div class="checkbox check-success">
                <input type="checkbox" checked="checked" value="ear_problem" id="ear_problem" name="cols_health[]">
                <label for="ear_problem">Ear Problem</label>
              </div> 

              <div class="checkbox check-success">
                <input type="checkbox" checked="checked" value="vision" id="vision" name="cols_health[]">
                <label for="vision">Vision</label>
              </div>

          </div>
         <div class="col-sm-3">       
             <div class="checkbox check-success">
                <input type="checkbox" checked="checked" value="eye_problem" id="eye_problem" name="cols_health[]">
                <label for="eye_problem">Eye Problem</label>
              </div>

              <div class="checkbox check-success">
                <input type="checkbox" checked="checked" value="jaundice" id="jaundice" name="cols_health[]">
                <label for="jaundice">Jaundice</label>
              </div>

            <div class="checkbox check-success">
                <input type="checkbox" checked="checked" value="facial_puffiness" id="facial_puffiness" name="cols_health[]">
                <label for="facial_puffiness">Facial Puffiness</label>
              </div>
            <div class="checkbox check-success">
                <input type="checkbox" checked="checked" value="mental_dissability" id="mental_dissability" name="cols_health[]">
                <label for="mental_dissability">Mental Disability</label>
              </div>
            <div class="checkbox check-success">
                <input type="checkbox" checked="checked" value="ho_immunisation" id="ho_immunisation" name="cols_health[]">
                <label for="ho_immunisation">HO Immunisation</label>
              </div>
              </div>
                  <div class="col-sm-3">       
            <div class="checkbox check-success">
                <input type="checkbox" checked="checked" value="ho_allergy" id="ho_allergy" name="cols_health[]">
                <label for="ho_allergy">HO Allergy</label>
              </div>
            <div class="checkbox check-success">
                <input type="checkbox" checked="checked" value="dental_problem" id="dental_problem" name="cols_health[]">
                <label for="dental_problem">Dental Problem</label>
              </div>
            <div class="checkbox check-success">
                <input type="checkbox" checked="checked" value="body_nits" id="body_nits" name="cols_health[]">
                <label for="body_nits">Body nits</label>
              </div>

               <div class="checkbox check-success">
                <input type="checkbox" checked="checked" value="lice_in_hair" id="lice_in_hair" name="cols_health[]">
                <label for="lice_in_hair">Lice In Hair</label>
              </div>

</div>
        <div class="col-sm-3">             
  
              <div class="checkbox check-success">
                <input type="checkbox" checked="checked" value="respiratory_infection" id="respiratory_infection" name="cols_health[]">
                <label for="respiratory_infection">Respiratory Infection</label>
              </div>

              <div class="checkbox check-success">
                <input type="checkbox" checked="checked" value="skin_problem" id="skin_problem" name="cols_health[]">
                <label for="skin_problem">Skin Problem</label>
              </div>
            
                <div class="checkbox check-success">
                <input type="checkbox" checked="checked" value="" id="students_check_all" >
                <label for="students_check_all">Select ALl</label>
              </div>
            
          </div>
        </div>
        </div>

      
      <div class="clearfix"></div>
      <button class="btn btn-primary" type="submit">Export</button>
    <% end %>
  </div>
</div>
<!-- END PANEL -->
</div>
</div>
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.min.css" rel="stylesheet" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.min.js"></script>

<script type="text/javascript">
  $(document).ready(function(){
    $("#school_check_all").click(function(){
    $('.school input:checkbox').not(this).prop('checked', this.checked);
  });
      $("#students_check_all").click(function(){
    $('.student input:checkbox').not(this).prop('checked', this.checked);
      });
      var URL = "/api/search_schools_for_select";
      $("#school_select").select2({
        minimumInputLength: 2,
        tags: [],
        ajax: {
            url: URL,
            dataType: 'json',
            type: "GET",
            quietMillis: 50,
            data: function (data) {
                return {
                    query: data
                };
            },
            processResults: function (data) {
              console.log(data);
                return {

                    results: $.map(data, function (item) {
                        return {
                            text: item.name,
                            id: item.id
                        }
                    })
                };
            }
        }
  });

   var URL2 = "/api/search_districts_for_select";
      $("#district_select").select2({
        minimumInputLength: 2,
        tags: [],
        ajax: {
            url: URL2,
            dataType: 'json',
            type: "GET",
            quietMillis: 50,
            data: function (data) {
                return {
                    query: data
                };
            },
            processResults: function (data) {
              console.log(data);
                return {

                    results: $.map(data, function (item) {
                        return {
                            text: item.name,
                            id: item.id
                        }
                    })
                };
            }
        }
  });

  var URL3 = "/api/search_tehsil_for_select";
      $("#tehsil_select").select2({
        minimumInputLength: 2,
        tags: [],
        ajax: {
            url: URL3,
            dataType: 'json',
            type: "GET",
            quietMillis: 50,
            data: function (data) {
                return {
                    query: data
                };
            },
            processResults: function (data) {
              console.log(data);
                return {

                    results: $.map(data, function (item) {
                        return {
                            text: item.name,
                            id: item.id
                        }
                    })
                };
            }
        }
  });


  });
  
  
</script> 

app/views/admin/_schools_table.html.erb
<div class="row">
  
<div class="col-md-8 col-md-offset-2">
    <!-- START PANEL -->
    <div class="panel panel-transparent">
      <div class="panel-heading">
        <div class="panel-title">List of Divisions
        </div>
      </div>
      <div class="panel-body">
        <div class="table-responsive">
          <div id="detailedTable_wrapper" class="dataTables_wrapper form-inline no-footer"><table class="table table-hover table-condensed table-detailed dataTable no-footer" id="detailedTable" role="grid">
            <thead>
              <tr role="row">
              <th style="width:50%" rowspan="1" colspan="1">Name</th>
              <th style="width:50%" rowspan="1" colspan="1">Delete</th>

              </tr>
            </thead>
            <tbody>
              
              
            <tr role="row" class="odd">
              <% @schools.each do |school| %>
                <td class="v-align-middle semi-bold"><%= school.name %></td>
                <td class="v-align-middle semi-bold"><%= school.tehsil.name %></td>
                <td class="v-align-middle"><%= link_to '<i class="fa fa-trash"></i>'.html_safe , admin_delete_school_path(school_id: school.id) %></td>
              </tr>
            <% end %>
              </tbody>
          </table></div>
        </div>
      </div>
    </div>
    <!-- END PANEL -->
  </div>
</div>  

app/views/admin/_side_bar_panel.html.erb
 <!-- BEGIN SIDEBPANEL-->
    <nav class="page-sidebar" data-pages="sidebar">
    
      <!-- BEGIN SIDEBAR MENU HEADER-->
      <div class="sidebar-header">
        <h1 style="color:white;">Reporting
        <div class="sidebar-header-controls">
          <button type="button" class="btn btn-link visible-lg-inline" data-toggle-pin="sidebar" title="Click to pin the side menu"><i class="fa fs-12"></i>
          </button>
          </h1>
        </div>
      </div>
      <!-- END SIDEBAR MENU HEADER-->
      <!-- START SIDEBAR MENU -->
      <div class="sidebar-menu">
        <!-- BEGIN SIDEBAR MENU ITEMS-->
        <ul class="menu-items">
          <li class="">
            <%= link_to admin_dashboard_path do %>
              <span class="title">Dashboard</span>
            <% end %>
            <span class="icon-thumbnail"><i class="pg-layouts"></i></span>
          </li>
          <li>
            <a href="javascript:;"><span class="title">Database</span>
            <span class=" arrow"></span></a>
            <span class="icon-thumbnail"><i class="pg-calender"></i></span>
            <ul class="sub-menu">
              <li class="">
              <%= link_to "Manage Divisions", admin_manage_divisions_path  %>
                <span class="icon-thumbnail">Di</span>
              </li> 
              <li class="">
              <%= link_to "Manage Districts", admin_manage_districts_path  %>
                <span class="icon-thumbnail">Ds</span>
              </li>
              <li class="">
              <%= link_to "Manage Tehsils", admin_manage_tehsils_path  %>
                <span class="icon-thumbnail">Th</span>
              </li>
            </ul>
          </li>
          <li class="">
            <%= link_to admin_manage_staff_path do %>
              <span class="title">Manage Staff</span>
            <% end %>
            <span class="icon-thumbnail"><i class="pg-layouts"></i></span>
          </li>
          
          <li class="">
            <%= link_to admin_manage_schools_path do %>
              <span class="title">Manage Schools</span>
            <% end %>
            <span class="icon-thumbnail"><i class="fa  fa-building"></i></span>
          </li>

          <li class="">
            <%= link_to admin_manage_shns_path do %>
              <span class="title">Manage SH&NS</span>
            <% end %>
            <span class="icon-thumbnail"><i class="pg-social"></i></span>
          </li>

          <li class="">
            <%= link_to admin_export_data_path do %>
              <span class="title">Export Data</span>
            <% end %>
            <span class="icon-thumbnail"><i class="pg-social"></i></span>
          </li>
          
          <li class="">
            <%= link_to admin_track_agents_path do %>
              <span class="title">Track Agents</span>
            <% end %>
            <span class="icon-thumbnail"><i class="pg-social"></i></span>
          </li>
          
        </ul>
        <div class="clearfix"></div>
      </div>
      <!-- END SIDEBAR MENU -->
    </nav>
    <!-- END SIDEBAR -->
    <!-- END SIDEBPANEL-->

app/views/admin/_staff_list.html.erb
<div class="row">
 
<div class="col-md-8 col-md-offset-2">
 <%= link_to admin_new_staff_member_path do %>
  <button class="btn btn-primary" type="submit">Add New Staff Member</button>
<% end %>
</div>
<div class="col-md-8 col-md-offset-2">
    <!-- START PANEL -->
    <div class="panel panel-transparent">
      <div class="panel-heading">
        <div class="panel-title"> <h1> Staff List </h1>
          
        </div>
      </div>
      <div class="panel-body">

          </div>
          <%= form_tag admin_manage_staff_path , :multipart => true ,role: "form",method: :get, novalidate: "novalidate", autocomplete: "off", id: "form-personal" do %>

             
              <div class="row">
                  <div class="col-sm-3">
                  <div class="form-group form-group-default required" aria-required="true">
                    <label>Select Role</label>
                      <%= select_tag 'role', content_tag(:option,'No Filter',:value=>"") + options_for_select(ROLES_FOR_STAFF, params[:role]) ,class: "form-control", required: "", id: "role"  %>
                  </div>
                </div>
            
                <div class="col-sm-3">
                <div class="form-group form-group-default " >
                  <label>Select Division</label>
                    <%= select_tag 'division',  content_tag(:option,'No Filter',:value=>"") +options_from_collection_for_select(Division.all,"id","name", params[:division]),class: "form-control", required: "" , id: "division" %>
                </div>
              </div>
            
                <div class="col-sm-3">
                <div class="form-group form-group-default " >
                  <label>Select District</label>
                    <%= select_tag 'district', content_tag(:option,'No Filter',:value=>"") + options_from_collection_for_select(District.filter_by_divisions(params[:division]),"id","name",params[:district]),class: "form-control", required: "", id: "district" %>
                </div>
              </div>
            
                <div class="col-sm-3">
                <div class="form-group form-group-default" >
                  <label>Select Tehsil</label>
                    <%= select_tag 'tehsil',  content_tag(:option,'No Filter',:value=>"") +options_from_collection_for_select(Tehsil.filter_by_districts(params[:district]),"id","name_with_district", params[:tehsil]),class: "form-control", required: "" %>
                </div>
              </div>


              <button class="btn btn-primary  pull-right" type="submit">Filter</button>
              <%= link_to "Clear Filter", admin_manage_staff_path, class: "btn btn-primary-clear pull-right" %>
              </div>

            <% end %>
        <div class="table-responsive">
          <div id="detailedTable_wrapper" class="dataTables_wrapper form-inline no-footer"><table class="table table-hover table-condensed table-detailed dataTable no-footer" id="detailedTable" role="grid">
            <thead>
              <tr role="row">
              <th style="width:50%" rowspan="1" colspan="1">Name</th>
              <th style="width:25%" rowspan="1" colspan="1">Role</th>
              <th style="width:25%" rowspan="1" colspan="1">Division/ Tehsil</th>
              <th style="width:25%" rowspan="1" colspan="1">Edit</th>
              <th style="width:25%" rowspan="1" colspan="1">Delete</th>
              <th style="width:25%" rowspan="1" colspan="1">Status(enabled/ disabled)</th>
              </tr>
            </thead>
            <tbody>
              
              
            <tr role="row" class="odd">
              <% @staff.each do |member| %>
                <td class="v-align-middle semi-bold"><%= member.name %></td>
                <td class="v-align-middle semi-bold"><%= member.role_name %></td>
                <td class="v-align-middle semi-bold"><%= member.place_name %></td>
                <td class="v-align-middle"><%= link_to '<i class="fa fa-wrench"></i>'.html_safe , admin_edit_staff_path(staff_id: member.id), remote: true %></td>
                <td class="v-align-middle"><%= link_to '<i class="fa fa-trash"></i>'.html_safe , admin_delete_staff_path(staff_id: member.id) %></td>
                <td> <input type="checkbox" data-init-plugin="switchery" data-size="small" class="switch" data-color="success" data-id="<%= member.id %>" <%= member.get_status_html %> />
            </td>
              </tr>

            <% end %>
              </tbody>
          </table></div>
        </div>
      </div>
    </div>
    <!-- END PANEL -->
  </div>
</div>  

<script type="text/javascript">
   $('#division').change(function() {
        $.ajax({
           url: "/admin/update_districts", // this will be routed
           type: 'GET',
           data: {
             division: $("#division").val()
           },
           async: true,
           dataType: "json",
           error: function(XMLHttpRequest, errorTextStatus, error){
                      alert("Failed: "+ errorTextStatus+" ;"+error);
                  },
           success: function(data){
              // here we iterate the json result
              document.getElementById('district').innerHTML = "";
              document.getElementById('tehsil').innerHTML = "";

              for(var i in data)
              {
                var id = data[i].id;
                var title = data[i].name;
                $("#district").append(new Option(title, id));
              }        
              $('#district').trigger("change");
           }
         });
      });

   $('#district').change(function() {
        $.ajax({
           url: "/admin/update_tehsils", // this will be routed
           type: 'GET',
           data: {
             district_id: $("#district").val()
           },
           async: true,
           dataType: "json",
           error: function(XMLHttpRequest, errorTextStatus, error){
                      alert("Failed: "+ errorTextStatus+" ;"+error);
                  },
           success: function(data){
              // here we iterate the json result
              document.getElementById('tehsil').innerHTML = "";

              for(var i in data)
              {
                var id = data[i].id;
                var title = data[i].name;
                $("#tehsil").append(new Option(title, id));
              }        
              // $('#tehsil1').trigger("change");
           }
         });
      });


</script>