config/routes.rb
Rails.application.routes.draw do
   get 'admin/login'
  get 'admin/logout'
  get 'admin/settings'
  get 'reports/students'
  get 'reports/schools'
  get 'reports/health_sessions'
  get 'reports/daily_community_visits'
  get 'reports/monthly_school_visits'
  get 'reports/daily_school_visits'
  get 'reports/environment_assessments'

  get 'admin/get_charts'
  get 'admin/update_tiles'
  get 'admin/update_movement_map'
  get 'admin/update_planning_report'
  get 'admin/update_tehsils'
  get 'admin/update_schools'
  get 'admin/update_districts'
  get 'admin/school_details'
  get 'admin/env_assesment_details'
  get 'admin/health_sessions_details'
  get 'admin/std_assesment_details'
  get 'admin/council_meetings_details'
  get 'admin/update_shns'
  get 'admin/update_movement_map'

  post 'admin/session_login'
  post 'admin/save_settings'

  get 'admin/manage_districts'
  get 'admin/manage_divisions'
  get 'admin/manage_ucs'
  get 'admin/edit_division'
  get 'admin/edit_tehsil'
  get 'admin/edit_district'
  get 'admin/edit_uc'
  get 'admin/delete_division'
  get 'admin/delete_district'
  get 'admin/delete_tehsil'
  get 'admin/delete_uc'
  get 'admin/delete_staff'
  get 'admin/manage_tehsils'

  get 'admin/manage_staff'
  get 'admin/manage_shns'
  get 'admin/manage_schools'
  get 'admin/delete_school'
  get 'admin/delete_shns'
  get 'admin/new_staff_member'
  get 'admin/edit_staff'
  get 'admin/new_shns_member'
  get 'admin/export_data'
  get 'admin/community_daily_reporting'
  get 'admin/monthly_school_visits'
  get 'admin/daily_school_visits'
  get 'admin/track_agents'

  get 'admin/division_details'
  get 'admin/district_details'
  get 'admin/tehsil_details'
  get 'admin/update_staff_status'
  get 'admin/school_details'

  post 'admin/create_new_school'
  post 'admin/create_new_shns'
  post 'admin/create_new_staff'
  post 'admin/export_data'
  post 'admin/create_new_district'
  post 'admin/update_district'
  post 'admin/update_staff'
  post 'admin/update_tehsil'
  post 'admin/create_new_division'
  post 'admin/update_division'
  post 'admin/update_uc'
  post 'admin/create_new_uc'
  post 'admin/create_new_tehsil'

  get 'admin/dashboard'
  get 'admin/new_agent'

  post 'api/login', :defaults => { :format => 'json' }
  post 'api/agent_location_log', :defaults => { :format => 'json' }
  post 'api/create_student', :defaults => { :format => 'json' }
  post 'api/get_nearby_schools', :defaults => { :format => 'json' }
  get 'api/search_schools_for_select', :defaults => { :format => 'json' }
  get 'api/search_tehsil_for_select', :defaults => { :format => 'json' }
  get 'api/search_districts_for_select', :defaults => { :format => 'json' }
  post 'api/search_schools', :defaults => { :format => 'json' }
  post 'api/search_uc', :defaults => { :format => 'json' }
  post 'api/get_ucs', :defaults => { :format => 'json' }
  post 'api/submit_health_session', :defaults => { :format => 'json' }
  post 'api/submit_child_health_screening', :defaults => { :format => 'json' }
  post 'api/submit_environment_assesment', :defaults => { :format => 'json' }
  post 'api/submit_council_meeting', :defaults => { :format => 'json' }
  post 'api/submit_add_child', :defaults => { :format => 'json' }
  post 'api/submit_planner_record', :defaults => { :format => 'json' }
  post 'api/submit_add_child_health_screening', :defaults => { :format => 'json' }

  get 'graph/students_assessed_by_day', :defaults => { :format => 'json' }
  get 'graph/followups_by_day', :defaults => { :format => 'json' }
  get 'graph/schools_visited_by_day', :defaults => { :format => 'json' }
  get 'graph/health_sessions_by_day', :defaults => { :format => 'json' }
  get 'graph/environmental_assesments_by_day', :defaults => { :format => 'json' }

  root 'admin#login'

end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :authenticate_admin, except: [:login,:session_login]
  before_action :load_admin, except: [:login, :session_login]
	
  def students
      @links_list = {
        "Dahsboard" => admin_dashboard_path,
        "Export Data" => admin_export_data_path,
       }
      respond_to do |format|
        format.xlsx {

        package = Axlsx::Package.new
            package.workbook do |wb|
                wb.add_worksheet do |sheet|
                row = params[:cols].split(',') + params[:cols_health].split(',')
                row =  row.map {|c| FRIENDLY_NAMES_REPORTS[c]}
                sheet.add_row row
                Student.create_excel_sheet params, sheet
            end
           end
         send_data package.to_stream.read, :filename => 'Students.xlsx', :type => "application/vnd.openxmlformates-officedocument.spreadsheetml.sheet"
       }

       format.html {

          @sheet = Student.create_excel params

       }
      end
    end

    def daily_community_visits
      
   
    end

   def daily_school_visits
     @links_list = {
        "Dahsboard" => admin_dashboard_path,
        "Export Reports" => admin_daily_school_visits_path,
    }
      @schools_visited = School.filter_by_range_visited params
      @environment_assessments = EnvironmentAssesment.filter params
      @heatlhs_screenings = ChildHealthScreening.filter(params).joins(:student)
      @follow_ups_today = FollowUp.filter(params)
      @children_screened_today = Student.filter_by_range_assesed params
      @uc_tehsil = Tehsil.where(id: params[:tehsil]) if params[:tehsil].present?
      @school = School.find_by_id(params[:school]) if params[:school].present?
      respond_to do |format|
      
       format.html {

          

       }
      end
    end


    def monthly_school_visits

	    respond_to do |format|
      
       format.html {

          

       }
    	end
  	end



  def schools
 @links_list = {
        "Dahsboard" => admin_dashboard_path,
        "Export Data" => admin_export_data_path,
    }
      respond_to do |format|
        format.xlsx {
        #       send_data Student.to_xlsx.to_stream.read, :filename => 'Students.xlsx', :type => "application/vnd.openxmlformates-officedocument.spreadsheetml.sheet"
        #  }  


        package = Axlsx::Package.new
            package.workbook do |wb|
                wb.add_worksheet do |sheet|
                row = params[:cols].split(',') + params[:cols_health].split(',') + params[:cols_env].split(',')
                row =  row.map {|c| FRIENDLY_NAMES_REPORTS[c]}
                sheet.add_row row

                School.create_excel_sheet params, sheet
            end
           end
         send_data package.to_stream.read, :filename => 'Schools.xlsx', :type => "application/vnd.openxmlformates-officedocument.spreadsheetml.sheet"
       }
       format.html {

          @sheet = School.create_excel params

       }
      end
    end

  	def health_sessions
  	    respond_to do |format|
        format.xlsx {
              send_data School.to_xlsx.to_stream.read, :filename => 'Schools.xlsx', :type => "application/vnd.openxmlformates-officedocument.spreadsheetml.sheet"
         }  
    	end
  	
  	end


	def environment_assessments
		respond_to do |format|
        format.xlsx {
              send_data School.to_xlsx.to_stream.read, :filename => 'Schools.xlsx', :type => "application/vnd.openxmlformates-officedocument.spreadsheetml.sheet"
         }  
    	end
	end

   def authenticate_admin
   if session[:admin].blank? || session[:new_check].blank?
      reset_session
      redirect_to({ :action=>'login' }, notice: 'Please login to conitnue.') 
   end
  end 

  def load_admin
    @links_list = {}
    @admin = Admin.find_by_id(session[:admin])
  end 

end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_community_report.html.erb
<div class="container-fluid container-fixed-lg">
            <div class="row">
              <div class="col-md-10 col-offset-md-2">
                <!-- START PANEL -->
                <div class="panel panel-transparent">
                  <div class="panel-heading">
                    <div class="panel-title">Community Daily Report
                    </div>
                    <div class="tools">
                      <a class="collapse" href="javascript:;"></a>
                      <a class="config" data-toggle="modal" href="#grid-config"></a>
                      <a class="reload" href="javascript:;"></a>
                      <a class="remove" href="javascript:;"></a>
                    </div>
                  </div>
                  <div class="panel-body" >
                    <div class="table-responsive" style="border:none;">
                      <table class="table table-striped" id="stripedTable">
                        <thead>
                        </thead>
                        <tr>
                          <td>Date</td>
                          <td><%= Date.today %></td>
                          <td>Name of Sh & NS</td>
                          <td><%= "_________" %></td>
                          <td>Contact No</td>
                          <td><%= "Contact No" %></td>
                        </tr>
                        <tr>
                          <td>LHW Name</td>
                          <td><%= "______" %></td>
                          <td>LHW Contact No</td>
                          <td><%= "_________" %></td>
                          <td>Name of U.C/ Tehsil No</td>
                          <td><%= "_______" %></td>
                        </tr>
                      </table>
                      </div>
                      <br/>
                      <div class="table-responsive" style="border:none;">
                      <table class="table table-striped" id="stripedTable">
                        <thead>
                       
                        </thead>
                        <tbody>
                        <tr style="font-size: 13px !important;
                        color: black;
                        font-weight: bold;
                        text-align: center;">
                          <td >Sr No.</td>
                          <td width="60%">Indicators</td>
                          <td colspan="3"><div class="row">
                              <div class="col-md-12" style="border-bottom: 1px solid black; padding: 2px;"><center>Numbers</center></div>
                              <div class="col-md-4" style=" padding: 2px;">M</div>
                              <div class="col-md-4" style="border-left: 1px solid black; padding: 2px;">F</div>
                              <div class="col-md-4" style="border-left: 1px solid black; padding: 2px;">Total</div>

                          </div></td>
                        </tr>
                       
                        <tr>
                          <td>1</td>
                          <td width="60%" >Total No. of Home Visited/Day</td>
                          <td><%= "__" %></td>
                          <td><%= "__" %></td>
                          <td><%= "__" %></td>
                        </tr>

                        <tr>
                          <td>2</td>
                          <td width="60%" >Total No. of Children Screened/Day</td>
                          <td><%= "__" %></td>
                          <td><%= "__" %></td>
                          <td><%= "__" %></td>
                        </tr>

                        <tr>
                          <td>3</td>
                          <td width="60%" >Total No. of Children Referred/Day</td>
                          <td><%= "__" %></td>
                          <td><%= "__" %></td>
                          <td><%= "__" %></td>
                        </tr>


                        <tr>
                          <td>4</td>
                          <td width="60%" >Total No. of Followup Cases/Day</td>
                          <td><%= "__" %></td>
                          <td><%= "__" %></td>
                          <td><%= "__" %></td>
                        </tr>

                        <tr>
                          <td>5</td>
                          <td width="60%" colspan="3">Total No. of Health Education Sessions Conducted/Day</td>
                          <td><%= "__" %></td>
                        </tr>

                         </tbody>

                      </table>
                    </div>
                      <br/>
                      <div class="table-responsive" style="border:none;">
                      <center style="color:black;"><strong><u>DETAILS OF HEALTH ISSUES IDENTIFIED</u></strong></center>
                      <table class="table table-striped" id="stripedTable">
                        <thead>
                        <th>Sr No.</th>
                        <th width="60%">Condition</th>
                        <th>M</th>
                        <th>F</th>
                        <th>Total</th>
                        </thead>
                        <tbody>

                        <tr>
                          <td>1</td>
                          <td width="60%" >Anemia</td>
                          <td><%= "__" %></td>
                          <td><%= "__" %></td>
                          <td><%= "__" %></td>
                        </tr>

                        <tr>
                          <td>2</td>
                          <td width="60%" >Jaundice</td>
                          <td><%= "__" %></td>
                          <td><%= "__" %></td>
                          <td><%= "__" %></td>
                        </tr>


                        <tr>
                          <td>3</td>
                          <td width="60%" >Facial Puffiness</td>
                          <td><%= "__" %></td>
                          <td><%= "__" %></td>
                          <td><%= "__" %></td>
                        </tr>

                        <tr>
                          <td>4</td>
                          <td width="60%" >Edema</td>
                          <td><%= "__" %></td>
                          <td><%= "__" %></td>
                          <td><%= "__" %></td>
                        </tr>

                        <tr>
                          <td>5</td>
                          <td width="60%" >Other Physical Deformities</td>
                          <td><%= "__" %></td>
                          <td><%= "__" %></td>
                          <td><%= "__" %></td>
                        </tr>

                        <tr>
                          <td>6</td>
                          <td width="60%" >Mental Disability Identification</td>
                          <td><%= "__" %></td>
                          <td><%= "__" %></td>
                          <td><%= "__" %></td>
                        </tr>

                        <tr>
                          <td>7</td>
                          <td width="60%" >Hearing Problem</td>
                          <td><%= "__" %></td>
                          <td><%= "__" %></td>
                          <td><%= "__" %></td>
                        </tr>


                        <tr>
                          <td>8</td>
                          <td width="60%" >Other Ear Problem</td>
                          <td><%= "__" %></td>
                          <td><%= "__" %></td>
                          <td><%= "__" %></td>
                        </tr>


                        <tr>
                          <td>9</td>
                          <td width="60%" >Vision, weak indecator( count on weak) , normal vision</td>
                          <td><%= "__" %></td>
                          <td><%= "__" %></td>
                          <td><%= "__" %></td>
                        </tr>


                        <tr>
                          <td>10</td>
                          <td width="60%" >Other Eye Problem</td>
                          <td><%= "__" %></td>
                          <td><%= "__" %></td>
                          <td><%= "__" %></td>
                        </tr>


                        <tr>
                          <td>11</td>
                          <td width="60%" >Acute Respiratory Infection</td>
                          <td><%= "__" %></td>
                          <td><%= "__" %></td>
                          <td><%= "__" %></td>
                        </tr>


                        <tr>
                          <td>12</td>
                          <td width="60%" >Skin Problem</td>
                          <td><%= "__" %></td>
                          <td><%= "__" %></td>
                          <td><%= "__" %></td>
                        </tr>

                        <tr>
                          <td>13</td>
                          <td width="60%" >Evidence of Trauma / Physical Injuries</td>
                          <td><%= "__" %></td>
                          <td><%= "__" %></td>
                          <td><%= "__" %></td>
                        </tr>

                        <tr>
                          <td>14</td>
                          <td width="60%" >HO Immunisation</td>
                          <td><%= "__" %></td>
                          <td><%= "__" %></td>
                          <td><%= "__" %></td>
                        </tr>

                        <tr>
                          <td>15</td>
                          <td width="60%" >HO Allergy</td>
                          <td><%= "__" %></td>
                          <td><%= "__" %></td>
                          <td><%= "__" %></td>
                        </tr>

                        <tr>
                          <td>16</td>
                          <td width="60%" >HO Hospitalisation</td>
                          <td><%= "__" %></td>
                          <td><%= "__" %></td>
                          <td><%= "__" %></td>
                        </tr>
                        
                         <tr>
                          <td>17</td>
                          <td width="60%" >BMI</td>
                          <td><%= "__" %></td>
                          <td><%= "__" %></td>
                          <td><%= "__" %></td>
                        </tr>

                         </tbody>

                      </table>
                    </div>
                    <br/>
                     <div class="table-responsive" style="border:none;">
                      <table class="table" id="stripedTable">
                        <thead>
                        </thead>
                        <tr>
                          <td>Signature</td>
                          <td><%= "________"%></td>

                          <td>Signature</td>
                          <td><%= "________"%></td>
                        </tr>

                        <tr>
                          <td></td>
                          <td>Lady Health Worker</td>

                          <td></td>
                          <td>School Health & Nutrition Supervisor</td>
                        </tr>


                        <tr>
                          <td>Date</td>
                          <td><%= "________"%></td>

                          <td>Date</td>
                          <td><%= "________"%></td>
                        </tr>

                        
                      </table>
                      </div>
                  </div>
                </div>
          </div>
    </div>
</div>

app/views/reports/_school_table.html.erb
 <div class="container-fluid container-fixed-lg">
            <div class="row">
              <div class="col-md-10 col-offset-md-2">
                <!-- START PANEL -->
                <div class="panel panel-transparent">
                  <div class="panel-heading">
                    <div class="panel-title">School Data
                    </div>
                    <div class="tools">
                      <a class="collapse" href="javascript:;"></a>
                      <a class="config" data-toggle="modal" href="#grid-config"></a>
                      <a class="reload" href="javascript:;"></a>
                      <a class="remove" href="javascript:;"></a>
                    </div>
                  </div>
                  <div class="panel-body">
                    <div class="table-responsive">
                      <table class="table table-striped" id="stripedTable">
                        <thead>
                          <tr>
                            <!-- NOTE * : Inline Style Width For Table Cell is Required as it may differ from user to user
												Comman Practice Followed
												--> 
                             <th style="width:10%">Name</th>
                            <th style="width:50%">Latitude</th>
                            <th style="width:40%">Longitude</th>
                            <th style="width:40%">Last Visited</th>
                            <th style="width:40%">Trauma/ Physical Injuries</th>
                            <th style="width:40%">BMI</th>
                            <th style="width:40%">Anemia</th>
                            <th style="width:40%">Physical Deformities</th>
                            <th style="width:40%">Physical Deformities</th>
                            <th style="width:40%">Hearing Problem</th>
                            <th style="width:40%">Ear Problem</th>
                            <th style="width:40%">Vision</th>
                            <th style="width:40%">Respiratory Infection</th>
                            <th style="width:40%">Skin Problem</th>
                            <th style="width:40%">Boundry Walls And Gate</th>
                            <th style="width:40%">Electricity playground</th>
                            <th style="width:40%">Clean Classes And Toilets</th>
                            <th style="width:40%">Clean Floors</th>
                            <th style="width:40%">Janitors</th>
                            <th style="width:40%">Ventilation</th>
                            <th style="width:40%">Tables And CHairs</th>
                            <th style="width:40%">Fans</th>
                            <th style="width:40%">Fountains</th>
                            <th style="width:40%">Clean Water</th>
                            <th style="width:40%">Adequate Supply</th>
                            <th style="width:40%">Functional Toilets</th>
                            <th style="width:40%">Numbers of Toilets</th>
                            <th style="width:40%">Soap Water in Toilets</th>
                            <th style="width:40%">Drainage</th>
                            <th style="width:40%">Functional Drainage</th>
                            <th style="width:40%">Waste Managment</th>
                            <th style="width:40%">Waste Managment Activity Frequency</th>
                          </tr>
                        </thead>
                        <tbody>
                          <% @sheet.each do |row| %>
                            <tr>
                            <% row.each do |col| %>
                              <td class="v-align-middle semi-bold">
                                <p><%= col %></p>
                              </td>
                            <% end %>
                            </tr>
                          <% end %>
                        </tbody>
                      </table>
                    </div>
                  </div>
                </div>
                <!-- END PANEL -->
              </div>
              <div class="col-md-12">
                 <dir class="col-md-12">
                  <%= form_tag reports_schools_path(format: "xlsx") , :multipart => true ,role: "form",method: :get, novalidate: "novalidate", autocomplete: "off", id: "form-personal" do %>
                     <%= hidden_field_tag "district", params[:district] %>
                     <%= hidden_field_tag "tehsil", params[:tehsil] %>
                     <%= hidden_field_tag "school", params[:school] %>
                     <%= hidden_field_tag "range", params[:range] %>
                     <%= hidden_field_tag "cols", params[:cols].join(',') %>
                     <%= hidden_field_tag "cols_health", params[:cols_health].join(',') %>
                     <%= hidden_field_tag "cols_env", params[:cols_env].join(',') %>
                  <button class="btn btn-primary" type="submit">Export</button>
                     
                  <% end %>

              </div>
            </div>
          </div>

app/views/reports/_student_table.html.erb
 <div class="container-fluid container-fixed-lg">
            <div class="row">
              <div class="col-md-10 col-offset-md-2">
                <!-- START PANEL -->
                <div class="panel panel-transparent">
                  <div class="panel-heading">
                    <div class="panel-title">Students Data
                    </div>
                    <div class="tools">
                      <a class="collapse" href="javascript:;"></a>
                      <a class="config" data-toggle="modal" href="#grid-config"></a>
                      <a class="reload" href="javascript:;"></a>
                      <a class="remove" href="javascript:;"></a>
                    </div>
                  </div>
                  <div class="panel-body">
                    <div class="table-responsive">
                      <table class="table table-striped" id="stripedTable">
                        <thead>
                          <tr>
                            <!-- NOTE * : Inline Style Width For Table Cell is Required as it may differ from user to user
												Comman Practice Followed
												--> 
                            <th style="width:10%">Name</th>
                            <th style="width:50%">Gaurdian's Name</th>
                            <th style="width:40%">Father's Name</th>
                            <th style="width:40%">Siblings</th>
                            <th style="width:40%">Height</th>
                            <th style="width:40%">Weight</th>
                            <th style="width:40%">Last Assessed</th>
                            <th style="width:40%">Trauma/ Physical Injuries</th>
                            <th style="width:40%">BMI</th>
                            <th style="width:40%">Anemia</th>
                            <th style="width:40%">Physical Deformities</th>
                            <th style="width:40%">Hearing Problem</th>
                            <th style="width:40%">Ear Problem</th>
                            <th style="width:40%">Vision</th>
                            <th style="width:40%">Respiratory Infection</th>
                            <th style="width:40%">Skin Problem</th>
                          </tr>
                        </thead>
                        <tbody>
                          <% @sheet.each do |row| %>
                            <tr>
                            <% row.each do |col| %>
                              <td class="v-align-middle semi-bold">
                                <p><%= col %></p>
                              </td>
                            <% end %>
                            </tr>
                          <% end %>
                        </tbody>
                      </table>


                    </div>
                  </div>
                </div>
                <!-- END PANEL -->
              </div>
              <dir class="col-md-12">
                  <%= form_tag reports_students_path(format: "xlsx") , :multipart => true ,role: "form",method: :get, novalidate: "novalidate", autocomplete: "off", id: "form-personal" do %>
                     <%= hidden_field_tag "district", params[:district] %>
                     <%= hidden_field_tag "tehsil", params[:tehsil] %>
                     <%= hidden_field_tag "school", params[:school] %>
                     <%= hidden_field_tag "range", params[:range] %>
                     <%= hidden_field_tag "cols", params[:cols].join(',') %>
                     <%= hidden_field_tag "cols_health", params[:cols_health].join(',') %>

                  <button class="btn btn-primary" type="submit">Export</button>

                  <% end %>

              </dir>
            </div>
          </div>

app/views/reports/daily_community_visits.html.erb
<!DOCTYPE html>
<html>
  <%= render 'admin/head' %>
  <body class="fixed-header dashboard horizontal-menu">
    <!-- START PAGE-CONTAINER -->
    <div class="page-container ">
      <!-- START HEADER -->
      <div class="header ">
        <!-- START MOBILE CONTROLS -->
        <div class="container-fluid relative">
          <!-- LEFT SIDE -->
          <div class="pull-left full-height visible-sm visible-xs">
            <!-- START ACTION BAR -->
            <div class="header-inner">
              <a href="#" class="btn-link toggle-sidebar visible-sm-inline-block visible-xs-inline-block padding-5" data-toggle="sidebar">
                <span class="icon-set menu-hambuger"></span>
              </a>
            </div>
            <!-- END ACTION BAR -->
          </div>
          <div class="pull-center ">
            <div class="header-inner">
              <div class="brand inline">
                <img src="/assets/img/logo_2x.png" alt="logo" data-src="/assets/img/logo_2x.png" data-src-retina="/assets/img/logo_2x.jpeg" >
              </div>
            </div>
          </div>
          <!-- RIGHT SIDE -->
          <div class="pull-right full-height visible-sm visible-xs">
            <!-- START ACTION BAR -->
            <div class="header-inner">
              <a href="#" class="btn-link visible-sm-inline-block visible-xs-inline-block" data-toggle="quickview" data-toggle-element="#quickview">
                <span class="icon-set menu-hambuger-plus"></span>
              </a>
            </div>
            <!-- END ACTION BAR -->
          </div>
        </div>
        <!-- END MOBILE CONTROLS -->
        <%= render 'admin/user_info' %>
      </div>
      <!-- END HEADER -->
      <!-- START PAGE CONTENT WRAPPER -->
      <div class="page-content-wrapper ">
        <!-- START PAGE CONTENT -->
        <div class="content sm-gutter">
        <%= render 'admin/top_bar' %>
          <!-- START CONTAINER FLUID -->
          <%= render 'community_report' %>
          <!-- END CONTAINER FLUID -->
        </div>
       <%= render 'admin/copyright' %>
      </div>
      <!-- END PAGE CONTENT WRAPPER -->
    </div>
    <!-- END PAGE CONTAINER -->
  <%= render 'admin/foot_js'  %>
 </body>
</html>